services:
    Mkk\TcpdfBundle\Service\TcpdfService:
        public: false
        arguments:
            - "@service_container"
            - "%mkk_tcpdf.class%"

    mkk_tcpdf.tcpdf:
        alias: Mkk\TcpdfBundle\Service\TcpdfService
        public: true
