language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION='3.4.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.0.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.1.*'
    - php: 7.2
      env: DEPENDENCIES='dev' SYMFONY_VERSION='4.1.*@dev'
  fast_finish: true

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"; fi;
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - composer install --dev

script: vendor/bin/phpunit