language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4
  - 8.0

matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION='5.3.*'
    - php: 7.3
      env: DEPENDENCIES='dev' SYMFONY_VERSION='5.4.*'
    - php: 7.4
      env: DEPENDENCIES='dev' SYMFONY_VERSION='5.4.*'
    - php: 8.0
      env: DEPENDENCIES='dev' SYMFONY_VERSION='5.4.*'
    - php: 8.0
      env: DEPENDENCIES='dev' SYMFONY_VERSION='6.0.*'
  fast_finish: true

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"; fi;
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - composer install --dev

script: vendor/bin/phpunit
